### ISSUE TITLE
Compatibility with Android 10

### ISSUE THREAD

**Issue by flojug** [bugnano/cordova-plugin-networking-bluetooth#3]
Please could you make it compatible with Android 10 .

The following function doesn't work anymore on Android 10 : networking.bluetooth.startDiscovery

See :
https://stackoverflow.com/questions/61792203/bluetooth-startdiscovery-is-not-working-on-android-10

I think the following permission should be added to the plugin.xml
`            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

And code modified to something like this (but it's not working) :
```
...
			if (cordova.hasPermission(Manifest.permission.ACCESS_COARSE_LOCATION) && cordova.hasPermission(Manifest.permission.ACCESS_FINE_LOCATION)) {
				this.startDiscovery(callbackContext);
			} else {
				this.getPermission(callbackContext, START_DISCOVERY_REQ_CODE, Manifest.permission.ACCESS_COARSE_LOCATION);
				this.getPermission(callbackContext, START_DISCOVERY_REQ_CODE, Manifest.permission.ACCESS_FINE_LOCATION);
			}
...
```

**Comment by bugnano** [comment]
Unfortunately I stopped developing for Android years ago, and that's why you see that the last commit for this project is from 2016.
That being said, I gladly accept PRs that fix issues like this one, or if someone wants to step up as a maintainer, I will give him/her the ownership of this repo, no problem.

**Comment by flojug** [comment]
OK I finally got it working with the following modifications :

In android.xml, add the line
`            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

And modify the "startDiscovery" part of the code :
```
		} else if (action.equals("startDiscovery")) {
			// Automatically cancel any previous discovery
			if (this.mBluetoothAdapter.isDiscovering()) {
				this.mBluetoothAdapter.cancelDiscovery();
			}

			if (!cordova.hasPermission(Manifest.permission.ACCESS_COARSE_LOCATION)) {
				this.getPermission(callbackContext, START_DISCOVERY_REQ_CODE, Manifest.permission.ACCESS_COARSE_LOCATION);
			} else if (!cordova.hasPermission(Manifest.permission.ACCESS_FINE_LOCATION)) {
				this.getPermission(callbackContext, START_DISCOVERY_REQ_CODE, Manifest.permission.ACCESS_FINE_LOCATION);
			} else {
				this.startDiscovery(callbackContext);
			}
			return true;
		} else if (action.equals("stopDiscovery")) {

```

**Comment by bugnano** [comment]
Perfect, if you make a pull request I will merge it.
Or if you want to become the new maintainer for this project, I will happily give it to you.
